### ISSUE TITLE
Can we do partial export?

### ISSUE THREAD

**Issue by osdaf** [pwwang/pyppl#10]
Like I just want to export part of the output files.  
For example:
```
p.output = "out1:file:somefile, out2:file:someotherfile"
```
I just want to export `out1`

**Comment by pwwang** [comment]
A temporary solution is to use `afterCmd`:
```python
p.afterCmd = 'cp {{proc.workdir}}/*/output/*.txt <exportdir>/'
```

**Comment by pwwang** [comment]
See documentation https://pwwang.gitbooks.io/pyppl/export-output-files.html#partial-export
