### ISSUE TITLE
Partial echo

### ISSUE THREAD

**Issue by osdaf** [pwwang/pyppl#13]
Proposed settings for `p.echo`:
```python
# echo all
p.echo = True
# don't echo anything
p.echo = False
# just echo stdout
p.echo = 'stdout'
# just echo stderr
p.echo = 'stderr'
```

**Comment by pwwang** [comment]
See documentation: https://pwwang.gitbooks.io/pyppl/content/set-other-properties-of-a-process.html#echo-jobs-stdoutstderr-to-log
