### ISSUE TITLE
Is it possible to add a function like proc.expect?

### ISSUE THREAD

**Issue by osdaf** [pwwang/pyppl#7]
Is it possible to have a function like that you can set:
```python
p = proc()
# ... 
p.expect = "grep <some string expected> {{outfile}}"
```
Sometime, even it returned 0 and output file generated, it could be still unexpected results.  
By this, you can set the expectation, tell `pyppl` whether the job is finished as we expected.

**Comment by pwwang** [comment]
Good catch, try to implement it in next version.
